### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by 350d** [rhysmorgan134/node-CarPlay#14]
Looks like it's possible to port whole project to browser (chrome) with WebUSB to communicate with usb dongle and decode video with WEB Codecs or any other js demuxer. 
I have two CarPlay dongles, not Android ones, will they work?

**Comment by jairajput** [comment]
You Can Use  HTML5 video element in combination with the Media Source Extensions

**Comment by steelbrain** [comment]
There's an implementation in `next` branch that uses WebUSB and can work entirely as a web-app.

This issue can therefore be closed (or kept open until the feature is released on npm).
