### ISSUE TITLE
Handle already initialised dongle in web

### ISSUE THREAD

**Issue by steelbrain** [rhysmorgan134/node-CarPlay#25]
This PR is about the new version of `node-carplay` in `next` branch for web version. Currently, even tho `.reset()` is called on the USB interface, it doesn't fully reset and keeps playing music if you reload the page with it.

What that means is that the video comes in, the audio comes in, but `Plugged` message does not. So there's two ways to handle this:

- Accept the dongle in its current state, and just mark the device as plugged if we're already getting audio and video
- Reset the dongle properly so we go through the expected sequence of events

cc @gozmanyoni

Edit: The implications here would be that we don't send the `pair` message after X seconds of boot

**Comment by gozmanyoni** [comment]
My thoughts are that its better to figure out its plugged and streaming and just mark it as plugged - that way we recover from a reload faster, if the device is healthy and sending us data we just start using it as is

What do you think @rhysmorgan134?

**Comment by rhysmorgan134** [comment]
Yeah I agree, feels the cleaner way to me to just have the data resume rather than a full reset.

**Comment by steelbrain** [comment]
Just to play the devil's advocate here, it's possible that the dongle already initialized doesn't match things like the wanted fps or the width/height, so it'll break expectations as the config will essentially be a no-op so isn't it a good idea to reset the dongle just to make sure the output is in the expected format?

**Comment by rhysmorgan134** [comment]
I completely agree this needs to be looked into, the APK has a bunch of references to canvas size change and various linked functions, so I do think this can be done dynamically rather than requiring a reset. What do you think about going ahead without a reset and tracking the dynamic functionality in an issue, if it turns out not possible then perhaps revisit?

I think it would be great for a parent application to be able to perhaps switch to a 50/50 view and have CarPlay scale dynamically (layout of CarPlay changes based on window size)

**Comment by steelbrain** [comment]
Just to add to the discussion, sometimes when resuming an already initialized dongle, I see a ton of `Invalid buffer size - Expecting 16, got ...`. Seems non fatal, but haven't dug into why they occur yet.

**Comment by gozmanyoni** [comment]
That's an error I added - if we read data from the usb dongle and its not header data  it will throw - after a few errors it will close the driver - its probably raw audio or video data its getting as its trying to read

**Comment by steelbrain** [comment]
> the APK has a bunch of references to canvas size change and various linked functions

It would be very interesting to explore the possibility of adaptive frame rates, if the device is fighting to handle it, we could keep lowering the FPS until it is stable

**Comment by gozmanyoni** [comment]
@steelbrain indeed - i wonder if its possible to adjust it without resetting the connection.

I do think its quite a nice-to-have feature rather than a crucial one - the usage of this is on car interfaces, where the consumer will usually fine-tune it to something that works well in all cases

**Comment by steelbrain** [comment]
Closing since a PR addressed it
