### ISSUE TITLE
Interface for subscribing to errors

### ISSUE THREAD

**Issue by steelbrain** [rhysmorgan134/node-CarPlay#38]
<img src="https://github.com/rhysmorgan134/node-CarPlay/assets/4278113/8569d72d-7a76-4014-94e3-25c46d102763">

We should have an API so consumers can subscribe to such errors (and attempt to recover by reloading the page, resetting the usb device etc)

**Comment by gozmanyoni** [comment]
The driver emits a failure event and closes - we can bubble that up

**Comment by gozmanyoni** [comment]
@steelbrain merged your PR - ok to close this?

**Comment by steelbrain** [comment]
Thanks and yes please
