### ISSUE TITLE
Replace pnpm with npm?

### ISSUE THREAD

**Issue by steelbrain** [rhysmorgan134/node-CarPlay#42]
Just opening an issue to gauge thoughts/interests in this. I think `pnpm` is nice, but for such few dependencies, and for an open source package, it's one extra thing contributors have to install.

What do you think about replacing it with plain npm?

**Comment by gozmanyoni** [comment]
I do prefer pnpm to npm (mainly due to performance and disk space) - but don't have a strong attachment to it, I wouldn't mind either way.

It is a small thing to install, and not an unknown package manager.

@rhysmorgan134 - what are your thoughts?

**Comment by steelbrain** [comment]
@gozmanyoni In that case, would it make sense to also use `pnpm` inside of the example?

**Comment by rhysmorgan134** [comment]
Personally I'd prefer npm, solely just due to knowing it's all already available and it's a pretty small package really. But pretty impartial either way.

**Comment by gozmanyoni** [comment]
Done in https://github.com/rhysmorgan134/node-CarPlay/pull/45 + Some ESM fixes.
