### ISSUE TITLE
Release next as semver-major

### ISSUE THREAD

**Issue by steelbrain** [rhysmorgan134/node-CarPlay#56]
Opening a tracking issue for releasing the current changeset in `next` as a semver-major release.

I've been daily driving it (the web version), and it's working pretty good for me.

I think it's good enough to be released to general public. Any shortcomings can be addressed in follow-up releases.

What do you think? @gozmanyoni @rhysmorgan134

**Comment by gozmanyoni** [comment]
I certainly think its publish ready - no major issues that I can see.

@steelbrain - curious, "pretty good" - what are some of the issues that still exist and can be improved?

The latest merge to next should have better memory management as video and audio streams are not cloned.

**Comment by steelbrain** [comment]
Heh, may have used confusing words.

I don't have any issues with the experience right now.

**Comment by rhysmorgan134** [comment]
I'm happy for it to go, easily more performant than the old version, and much more stable, even from my limited testing. Excited to see what can come from it!

**Comment by steelbrain** [comment]
@rhysmorgan134 The PR is merged, could you please release it on NPM?

**Comment by gozmanyoni** [comment]
🥳 https://www.npmjs.com/package/node-carplay/v/4.0.0
