### ISSUE TITLE
Unable to set icon for car button

### ISSUE THREAD

**Issue by steelbrain** [rhysmorgan134/node-CarPlay#64]
I used the integrated `configIcon.ts` script and all I'm getting is what's in the screenshot below.

Is there an example icon file that works fine?

<img src="https://github.com/rhysmorgan134/node-CarPlay/assets/4278113/281a2172-66ee-45ac-9ae6-4bbe0edc435a">

**Comment by gozmanyoni** [comment]
@steelbrain what resolution/file extension did you have?

**Comment by steelbrain** [comment]
@gozmanyoni I used a png file in 256x256, then modified the code to point to two other files that are 120 and 180.

**Comment by gozmanyoni** [comment]
@steelbrain hmm, we might need to also write the 256x256 image to the oem_icon path, could you try that:

`await driver.send(new SendFile(iconBuff, FileAddress.OEM_ICON))`

**Comment by steelbrain** [comment]
@gozmanyoni No dice, is it working for you locally?

**Comment by steelbrain** [comment]
Okay so this is embarassing but I tried a non-transparent PNG and it finally worked :)
Apologies. Closing the issue. I also did it with the OEM_ICON, not sure if that helped
