### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by abuharsky** [rhysmorgan134/node-CarPlay#78]
Hi, for some reason video not playing from node app on my car Head Unit browser. 

Is it possible to stream it as sequense of images, that can be rendered inside <image src...?

what type of data inside message with type "Video"?

**Comment by abuharsky** [comment]
`camera.html

<!DOCTYPE html>
<html>

<head>
    <title>ipCam</title>
</head>

<body>
    <h1>ipCam</h1>
    <img id="motionjpeg" src="http://user:pass@127.0.0.1:8080/" />
    <script src="motionjpeg.js"></script>
    <script>
        //Using jQuery for simplicity

        $(document).ready(function() {
            motionjpeg("#motionjpeg"); // Use the function on the image
        });
    </script>
</body>

</html>
motionjpeg.js

function motionjpeg(id) {
    var image = $(id), src;

    if (!image.length) return;

    src = image.attr("src");
    if (src.indexOf("?") < 0) {
        image.attr("src", src + "?"); // must have querystring
    }

    image.on("load", function() {
        // this cause the load event to be called "recursively"
        this.src = this.src.replace(/\?[^\n]*$/, "?") +
            (new Date()).getTime(); // 'this' refers to the image
    });
}`

**Comment by abuharsky** [comment]
Something like this


this

camera.html

<!DOCTYPE html>
<html>

<head>
    <title>ipCam</title>
</head>

<body>
    <h1>ipCam</h1>
    <img id="motionjpeg" src="http://user:pass@127.0.0.1:8080/" />
    <script src="motionjpeg.js"></script>
    <script>
        //Using jQuery for simplicity

        $(document).ready(function() {
            motionjpeg("#motionjpeg"); // Use the function on the image
        });
    </script>
</body>

</html>
motionjpeg.js

function motionjpeg(id) {
    var image = $(id), src;

    if (!image.length) return;

    src = image.attr("src");
    if (src.indexOf("?") < 0) {
        image.attr("src", src + "?"); // must have querystring
    }

    image.on("load", function() {
        // this cause the load event to be called "recursively"
        this.src = this.src.replace(/\?[^\n]*$/, "?") +
            (new Date()).getTime(); // 'this' refers to the image
    });
}




https://stackoverflow.com/questions/19346775/rendering-mjpeg-stream-in-html5

**Comment by steelbrain** [comment]
> Hi, for some reason video not playing from node app on my car Head Unit browser.

Does any h264 video play at all in your browser? If not, I think it may be easier/simpler to fix that instead of trying to render a sequence of h264 frames as images

**Comment by abuharsky** [comment]
This one works

https://html5videoplayer.net/html5video/mp4-h-264-video-test/

**Comment by abuharsky** [comment]
![IMG_4730](https://github.com/rhysmorgan134/node-CarPlay/assets/733130/ff598d41-9725-41b3-a9c1-07d682608535)

**Comment by abuharsky** [comment]
Jmuxer sample not working


![IMG_4732](https://github.com/rhysmorgan134/node-CarPlay/assets/733130/325bae28-f77a-42da-aa78-5e84b19b2aa2)

**Comment by steelbrain** [comment]
@abuharsky Is it possible at all to get some console logs from that browser? That would help us understand a bit more about *why* it's failing. Also if you could check if the browser has a `chrome://gpu` or `about:support` page, a screenshot of that would be helpful as well
