### ISSUE TITLE
Where are CarPlay font sizes set?

### ISSUE THREAD

**Issue by psmith3** [rhysmorgan134/node-CarPlay#8]
Hi, I am working on implementing marcdubois71450/tesla-carplay that is forked from your project if I recall. I know that is not your project, but I was wondering if you might have some answers that are related to node-CarPlay. 

I have set the canvas size to 1180x960 and now I am seeing the album and track name fonts being scaled too big. Do you have any idea what values set these items? I believe these values are set in jsmpeg.min.js. See my attached screenshot showing the oversized fonts. 

On a separate issue, I am also trying to determine where the touch overlay map is that sets where the touch buttons are on the screen. Not all my touch locations line up and it seems to also be resolution related. 

Not sure if you would know either of my questions, but thank you in advance. 

![image](https://user-images.githubusercontent.com/14373163/161398757-8498bcb0-fc75-49b3-96d1-9a26fba753b9.jpeg)

**Comment by rhysmorgan134** [comment]
Hi,

It seems like Marcs implementation is not a fork, but rather a copy and paste of most of the code from this package, I would suggest you ask on that repo for support regarding the issues here.
