### ISSUE TITLE
Multitouch Issue in own App since latest release

### ISSUE THREAD

**Issue by LRYMND** [rhysmorgan134/node-CarPlay#84]
I have a react web app that uses node-carplay for Apple Carplay.

Before multitouch was released everyhing worked fine. I wanted to upgrade to the latest version now but I can't interact with Carplay anymore. I'm no web-developer so it's a little bit harder for me to trace down the issue, also since everything is packed up now a bit differently.

When running the web-app example it works, not in my own app though. I changed the location of some files a bit, updated the imports but besides that I'm using 1:1 the same codebase. I loose the trace after the useCarplayTouch.ts file. In there it's calling sendTouchEvent which should send the touchEvent to the node-carplay module which then sends it to the dongle.

I can see that sendTouchEvent is being called. When I console.log in the sendable.js from the node_modules folder, I can see a log in the web-app example. In my app I don't see the log at the same spot. I'm not sure what could cause this. A wrong tsconfig or vite.config file?

I made sure to meticulously copy over every change from the latest release. Stream and everything works fine, I just can't click or "touch" anything when carplay has launched.

If I can add filecontents or any other information please let me know.

**Comment by gozmanyoni** [comment]
There have been a few complains about the multi touch changes, I have reverted them, latest master should work as it worked before with touch events

**Comment by LRYMND** [comment]
That fixed the issue indeed, thank you.

I noticed that it  stopped working, once I migrated from react-app-rewired to vite. Maybe that serves as a clue for you. Didnt do further investigation though.
