### ISSUE TITLE
Carlink 5.0 2Air Wireless support

### ISSUE THREAD

**Issue by martin2131** [rhysmorgan134/node-CarPlay#88]
Hi, has anyone had any success connecting to the Carlink 5.0 2Air Wireless? If so, can I ask for intructions? :)

In lsusb it's like this:
Bus 003 Device 003: ID 05ac:12a8 Apple, Inc. iPhone 5/5C/5S/6/SE/7/8/X/XR

**Comment by gozmanyoni** [comment]
Hi @martin2131 , only CPC200-Autokit or CPC200-CCPA are supported
